# Generated by Django 4.0 on 2024-05-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='name',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(default=9, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
            preserve_default=False,
        ),
    ]
